/**
 * Cubicación (Quantity Takeoff) Types
 *
 * Types for automatic quantity extraction from infrastructure elements
 * and integration with SERVIU itemizado for cost estimation
 */

// ============================================================================
// Cubicación Item Types
// ============================================================================

export type CubicacionCategory =
  | 'excavacion'      // Excavation
  | 'relleno'         // Backfill
  | 'cama'            // Bedding
  | 'tuberia'         // Pipes
  | 'camaras'         // Manholes/chambers
  | 'sumideros'       // Inlets
  | 'conexiones'      // Connections
  | 'pavimentos'      // Pavements
  | 'obras_civiles'   // Civil works
  | 'varios';         // Miscellaneous

export type MeasurementUnit =
  | 'm'     // Linear meter
  | 'm2'    // Square meter
  | 'm3'    // Cubic meter
  | 'un'    // Unit
  | 'kg'    // Kilogram
  | 'gl'    // Global
  | 'ml'    // Linear meter (alternative)
  | 'ton';  // Ton

export interface CubicacionItem {
  id: string;
  serviuCode: string;           // SERVIU itemizado code (e.g., "301.1")
  description: string;          // Full description
  shortDescription?: string;    // Short name for tables
  category: CubicacionCategory;
  unit: MeasurementUnit;
  quantity: number;
  unitPrice: number;            // CLP
  totalPrice: number;           // quantity * unitPrice

  // Traceability
  sourceEntityIds: string[];    // Infrastructure entity IDs this came from
  calculationDetails?: string;  // How the quantity was calculated

  // Override flags
  isManualOverride: boolean;    // User modified the quantity
  autoCalculated: boolean;      // Generated from entities

  // Metadata
  notes?: string;
  lastUpdated: string;
}

export interface CubicacionSubtotal {
  category: CubicacionCategory;
  categoryLabel: string;
  total: number;
  percentage: number;
  itemCount: number;
}

export interface Cubicacion {
  id: string;
  projectId: string;
  name: string;
  version: number;
  status: 'draft' | 'review' | 'approved' | 'final';

  // Items
  items: CubicacionItem[];
  subtotals: CubicacionSubtotal[];
  grandTotal: number;

  // Pricing reference
  priceDate: string;            // Date of prices used
  priceSource: string;          // "SERVIU RM 2024", etc.
  currency: 'CLP' | 'UF';
  ufValue?: number;             // UF value at priceDate

  // Metadata
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
  approvedBy?: string;
  approvalDate?: string;

  // Auto-generation state
  lastAutoGenerated?: string;
  autoGenerationEnabled: boolean;
}

// ============================================================================
// Calculation Parameters
// ============================================================================

export interface ExcavationParams {
  pipeDepth: number;            // m - depth to pipe invert
  trenchWidth: number;          // m - total trench width
  pipeOuterDiameter: number;    // m
  slopeAngle?: number;          // degrees - for sloped walls
  overtapado?: number;          // m - additional cover above pipe
}

export interface BeddingParams {
  thickness: number;            // m - bedding thickness
  width: number;                // m - bedding width
  material: 'sand' | 'gravel' | 'stabilized';
}

export interface BackfillParams {
  compactedLayers: number;      // Number of compacted layers
  layerThickness: number;       // m - each layer thickness
  compactionDegree: number;     // % Proctor
  material: 'selected' | 'imported' | 'granular';
}

export interface ManholeParams {
  type: 'A' | 'B' | 'C' | 'drop';
  depth: number;                // m
  internalDiameter: number;     // m
  wallThickness: number;        // m
  baseThickness: number;        // m
  coverType: 'D400' | 'D250' | 'B125';
}

// ============================================================================
// Generator Configuration
// ============================================================================

export interface CubicacionGeneratorConfig {
  // Excavation parameters
  defaultTrenchWidthFactor: number;     // Multiplier of pipe diameter
  minTrenchWidth: number;               // m
  defaultSlopeAngle: number;            // degrees (0 for vertical)
  defaultOvertapado: number;            // m - cover above pipe crown

  // Bedding
  defaultBeddingThickness: number;      // m
  beddingWidthFactor: number;           // Multiplier of pipe diameter

  // Backfill
  defaultCompactionLayers: number;
  defaultLayerThickness: number;        // m
  defaultCompactionDegree: number;      // %

  // Materials
  defaultPipeMaterial: string;
  defaultBeddingMaterial: 'sand' | 'gravel';

  // Pricing
  applyContingency: boolean;
  contingencyPercent: number;           // %

  // Rounding
  roundQuantities: boolean;
  quantityDecimals: number;
}

export const DEFAULT_GENERATOR_CONFIG: CubicacionGeneratorConfig = {
  defaultTrenchWidthFactor: 2.5,        // Pipe D + 2*0.75D working space
  minTrenchWidth: 0.6,                  // 60cm minimum
  defaultSlopeAngle: 0,                 // Vertical walls
  defaultOvertapado: 1.0,               // 1m cover

  defaultBeddingThickness: 0.15,        // 15cm
  beddingWidthFactor: 1.5,

  defaultCompactionLayers: 4,
  defaultLayerThickness: 0.20,          // 20cm layers
  defaultCompactionDegree: 95,

  defaultPipeMaterial: 'PVC',
  defaultBeddingMaterial: 'sand',

  applyContingency: false,
  contingencyPercent: 10,

  roundQuantities: true,
  quantityDecimals: 2,
};

// ============================================================================
// Category Labels
// ============================================================================

export const CATEGORY_LABELS: Record<CubicacionCategory, string> = {
  excavacion: 'Excavaciones',
  relleno: 'Rellenos',
  cama: 'Camas de Apoyo',
  tuberia: 'Tuberías',
  camaras: 'Cámaras y Pozos',
  sumideros: 'Sumideros e Imbornales',
  conexiones: 'Conexiones Domiciliarias',
  pavimentos: 'Pavimentos',
  obras_civiles: 'Obras Civiles',
  varios: 'Varios',
};

// ============================================================================
// API Types
// ============================================================================

export interface CreateCubicacionRequest {
  projectId: string;
  name: string;
  autoGenerate?: boolean;
}

export interface UpdateCubicacionRequest {
  name?: string;
  status?: Cubicacion['status'];
  items?: CubicacionItem[];
}

export interface GenerateCubicacionRequest {
  projectId: string;
  config?: Partial<CubicacionGeneratorConfig>;
}

export interface CubicacionResponse {
  cubicacion: Cubicacion;
}

export interface CubicacionListResponse {
  cubicaciones: Cubicacion[];
  total: number;
}
