'use client';

/**
 * Design Criteria Editor Component
 *
 * Edits design criteria content for engineering documents.
 * Includes hydraulic parameters, material specs, and normative references.
 */

import { useCallback } from 'react';
import type { DesignCriteriaContent } from '@/types/documents';

interface DesignCriteriaEditorProps {
  content: DesignCriteriaContent;
  onChange: (content: DesignCriteriaContent) => void;
  readOnly?: boolean;
}

const PROJECT_TYPE_LABELS: Record<string, string> = {
  alcantarillado: 'Alcantarillado',
  agua_potable: 'Agua Potable',
  aguas_lluvias: 'Aguas Lluvias',
  pavimentacion: 'Pavimentación',
  mixto: 'Proyecto Mixto',
};

const COMMON_NORMS = [
  { code: 'NCh 1105', title: 'Alcantarillado de aguas residuales' },
  { code: 'NCh 691', title: 'Agua potable - Conducción y distribución' },
  { code: 'NCh 2472', title: 'Cámaras de inspección prefabricadas' },
  { code: 'RIDAA', title: 'Reglamento Instalaciones Domiciliarias AP y AS' },
  { code: 'Manual MINVU', title: 'Manual de Drenaje Urbano MINVU' },
  { code: 'MOP Vol. 3', title: 'Manual de Carreteras - Diseño' },
  { code: 'AASHTO 93', title: 'Diseño de Pavimentos AASHTO' },
];

export function DesignCriteriaEditor({ content, onChange, readOnly = false }: DesignCriteriaEditorProps) {
  const updateField = useCallback(<K extends keyof DesignCriteriaContent>(
    field: K,
    value: DesignCriteriaContent[K]
  ) => {
    if (readOnly) return;
    onChange({ ...content, [field]: value, autoGenerated: false });
  }, [content, onChange, readOnly]);

  const updateHydraulicCriteria = useCallback((
    field: string,
    value: number | undefined
  ) => {
    if (readOnly) return;
    onChange({
      ...content,
      hydraulicCriteria: {
        ...content.hydraulicCriteria,
        [field]: value,
      },
      autoGenerated: false,
    });
  }, [content, onChange, readOnly]);

  const updateMaterials = useCallback((
    field: string,
    value: string | number | undefined
  ) => {
    if (readOnly) return;
    onChange({
      ...content,
      materials: {
        ...content.materials,
        [field]: value,
      },
      autoGenerated: false,
    });
  }, [content, onChange, readOnly]);

  const toggleNorm = useCallback((normCode: string) => {
    if (readOnly) return;
    const currentNorms = content.applicableNorms || [];
    const newNorms = currentNorms.includes(normCode)
      ? currentNorms.filter(n => n !== normCode)
      : [...currentNorms, normCode];
    onChange({ ...content, applicableNorms: newNorms, autoGenerated: false });
  }, [content, onChange, readOnly]);

  const hc = content.hydraulicCriteria || {};
  const mat = content.materials || {};

  return (
    <div className="design-criteria-editor space-y-6">
      {/* Auto-generated indicator */}
      {content.autoGenerated && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
          <span className="text-sm text-blue-800">
            ⚙️ Criterios predefinidos según tipo de proyecto. Puedes modificarlos.
          </span>
        </div>
      )}

      {/* Project Type & Period */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Tipo de Proyecto
        </legend>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Tipo</label>
            <select
              value={content.projectType}
              onChange={(e) => updateField('projectType', e.target.value as DesignCriteriaContent['projectType'])}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            >
              {Object.entries(PROJECT_TYPE_LABELS).map(([key, label]) => (
                <option key={key} value={key}>{label}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Período de Diseño (años)</label>
            <input
              type="number"
              value={content.designPeriod}
              onChange={(e) => updateField('designPeriod', parseInt(e.target.value) || 20)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
          <div className="col-span-2">
            <label className="block text-xs text-gray-500 mb-1">Horizonte de Diseño</label>
            <input
              type="text"
              value={content.designHorizon}
              onChange={(e) => updateField('designHorizon', e.target.value)}
              placeholder="Ej: 2024-2044"
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
        </div>
      </fieldset>

      {/* Hydraulic Criteria - Sewer/Combined */}
      {(content.projectType === 'alcantarillado' || content.projectType === 'mixto') && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Criterios Hidráulicos - Alcantarillado
          </legend>

          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Vel. Mínima (m/s)</label>
              <input
                type="number"
                value={hc.minVelocity || ''}
                onChange={(e) => updateHydraulicCriteria('minVelocity', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.1"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Vel. Máxima (m/s)</label>
              <input
                type="number"
                value={hc.maxVelocity || ''}
                onChange={(e) => updateHydraulicCriteria('maxVelocity', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.1"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Pendiente Mín. (%)</label>
              <input
                type="number"
                value={hc.minSlope || ''}
                onChange={(e) => updateHydraulicCriteria('minSlope', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.01"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Llenado Máx. (0-1)</label>
              <input
                type="number"
                value={hc.maxFillRatio || ''}
                onChange={(e) => updateHydraulicCriteria('maxFillRatio', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.05"
                min="0"
                max="1"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">n Manning</label>
              <input
                type="number"
                value={hc.manningN || ''}
                onChange={(e) => updateHydraulicCriteria('manningN', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.001"
                disabled={readOnly}
              />
            </div>
          </div>
        </fieldset>
      )}

      {/* Hydraulic Criteria - Water */}
      {(content.projectType === 'agua_potable' || content.projectType === 'mixto') && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Criterios Hidráulicos - Agua Potable
          </legend>

          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Presión Mín. (m.c.a.)</label>
              <input
                type="number"
                value={hc.minPressure || ''}
                onChange={(e) => updateHydraulicCriteria('minPressure', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Presión Máx. (m.c.a.)</label>
              <input
                type="number"
                value={hc.maxPressure || ''}
                onChange={(e) => updateHydraulicCriteria('maxPressure', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">C Hazen-Williams</label>
              <input
                type="number"
                value={hc.hazenWilliamsC || ''}
                onChange={(e) => updateHydraulicCriteria('hazenWilliamsC', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
          </div>
        </fieldset>
      )}

      {/* Hydraulic Criteria - Stormwater */}
      {(content.projectType === 'aguas_lluvias' || content.projectType === 'mixto') && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Criterios Hidráulicos - Aguas Lluvias
          </legend>

          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Período Retorno (años)</label>
              <input
                type="number"
                value={hc.returnPeriod || ''}
                onChange={(e) => updateHydraulicCriteria('returnPeriod', parseInt(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Coef. Escorrentía</label>
              <input
                type="number"
                value={hc.runoffCoefficient || ''}
                onChange={(e) => updateHydraulicCriteria('runoffCoefficient', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.05"
                min="0"
                max="1"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Tc (min)</label>
              <input
                type="number"
                value={hc.timeOfConcentration || ''}
                onChange={(e) => updateHydraulicCriteria('timeOfConcentration', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
          </div>
        </fieldset>
      )}

      {/* Material Specifications */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Especificaciones de Materiales
        </legend>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Material Tuberías</label>
            <select
              value={mat.pipeMaterial || ''}
              onChange={(e) => updateMaterials('pipeMaterial', e.target.value)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            >
              <option value="">Seleccionar...</option>
              <option value="PVC">PVC</option>
              <option value="HDPE">HDPE (Polietileno)</option>
              <option value="Hormigón">Hormigón</option>
              <option value="Fierro Dúctil">Fierro Dúctil</option>
              <option value="Acero">Acero</option>
            </select>
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Clase/Serie</label>
            <input
              type="text"
              value={mat.pipeClass || ''}
              onChange={(e) => updateMaterials('pipeClass', e.target.value)}
              placeholder="Ej: Clase 6, SDR 21"
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Diámetro Mínimo (mm)</label>
            <input
              type="number"
              value={mat.minDiameter || ''}
              onChange={(e) => updateMaterials('minDiameter', parseInt(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Tipo de Unión</label>
            <input
              type="text"
              value={mat.jointType || ''}
              onChange={(e) => updateMaterials('jointType', e.target.value)}
              placeholder="Ej: Goma, Soldada"
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
        </div>
      </fieldset>

      {/* Applicable Norms */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Normas Aplicables
        </legend>

        <div className="space-y-2">
          {COMMON_NORMS.map((norm) => (
            <label key={norm.code} className="flex items-center gap-2 text-sm">
              <input
                type="checkbox"
                checked={content.applicableNorms.includes(norm.code)}
                onChange={() => toggleNorm(norm.code)}
                className="rounded"
                disabled={readOnly}
              />
              <span className="font-medium">{norm.code}</span>
              <span className="text-gray-500">- {norm.title}</span>
            </label>
          ))}
        </div>
      </fieldset>
    </div>
  );
}

export default DesignCriteriaEditor;
