'use client';

/**
 * Infrastructure Summary Display Component
 *
 * Displays auto-generated infrastructure summary from project entities.
 * Shows pipes, manholes, stormwater elements, and quantities summary.
 * This is primarily read-only as it pulls from the project data.
 */

import type { InfrastructureSummaryContent } from '@/types/documents';

interface InfrastructureSummaryDisplayProps {
  content: InfrastructureSummaryContent;
  onChange?: (content: InfrastructureSummaryContent) => void;
  readOnly?: boolean;
}

export function InfrastructureSummaryDisplay({ content, onChange, readOnly = true }: InfrastructureSummaryDisplayProps) {
  const { pipes, nodes, stormwater, quantitiesSummary } = content;

  const handleRefresh = () => {
    if (onChange && !readOnly) {
      // This would trigger a re-fetch from the project data
      // The actual refresh happens in the parent component
      onChange({ ...content, autoGenerated: true });
    }
  };

  return (
    <div className="infrastructure-summary-display space-y-6">
      {/* Auto-generated indicator */}
      {content.autoGenerated && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-3 flex items-center justify-between">
          <span className="text-sm text-green-800">
            🔄 Resumen generado automáticamente desde las entidades del proyecto.
          </span>
          {!readOnly && onChange && (
            <button
              type="button"
              onClick={handleRefresh}
              className="px-3 py-1 text-xs bg-green-100 border border-green-300 rounded hover:bg-green-200"
            >
              Actualizar
            </button>
          )}
        </div>
      )}

      {/* Pipes Summary */}
      {pipes && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Red de Tuberías
          </legend>

          <div className="space-y-4">
            {/* Overview */}
            <div className="grid grid-cols-4 gap-4 text-center">
              <div className="bg-blue-50 p-3 rounded-lg">
                <div className="text-2xl font-bold text-blue-700">
                  {pipes.totalLength?.toFixed(1) || 0}
                </div>
                <div className="text-xs text-gray-600">Longitud Total (m)</div>
              </div>
              <div className="bg-blue-50 p-3 rounded-lg">
                <div className="text-2xl font-bold text-blue-700">
                  {pipes.minDiameter || 0}
                </div>
                <div className="text-xs text-gray-600">Ø Mínimo (mm)</div>
              </div>
              <div className="bg-blue-50 p-3 rounded-lg">
                <div className="text-2xl font-bold text-blue-700">
                  {pipes.maxDiameter || 0}
                </div>
                <div className="text-xs text-gray-600">Ø Máximo (mm)</div>
              </div>
              <div className="bg-blue-50 p-3 rounded-lg">
                <div className="text-2xl font-bold text-blue-700">
                  {Object.keys(pipes.byDiameter || {}).length}
                </div>
                <div className="text-xs text-gray-600">Tipos de Ø</div>
              </div>
            </div>

            {/* By Diameter Table */}
            {pipes.byDiameter && Object.keys(pipes.byDiameter).length > 0 && (
              <div>
                <h4 className="text-xs font-medium text-gray-600 mb-2">Por Diámetro</h4>
                <table className="w-full text-sm border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border px-3 py-1 text-left">Diámetro (mm)</th>
                      <th className="border px-3 py-1 text-right">Longitud (m)</th>
                      <th className="border px-3 py-1 text-right">%</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(pipes.byDiameter)
                      .sort(([a], [b]) => Number(a) - Number(b))
                      .map(([dia, len]) => (
                        <tr key={dia}>
                          <td className="border px-3 py-1">Ø {dia}</td>
                          <td className="border px-3 py-1 text-right">{len.toFixed(2)}</td>
                          <td className="border px-3 py-1 text-right">
                            {((len / (pipes.totalLength || 1)) * 100).toFixed(1)}%
                          </td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* By Material Table */}
            {pipes.byMaterial && Object.keys(pipes.byMaterial).length > 0 && (
              <div>
                <h4 className="text-xs font-medium text-gray-600 mb-2">Por Material</h4>
                <table className="w-full text-sm border-collapse">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="border px-3 py-1 text-left">Material</th>
                      <th className="border px-3 py-1 text-right">Longitud (m)</th>
                      <th className="border px-3 py-1 text-right">%</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(pipes.byMaterial).map(([mat, len]) => (
                      <tr key={mat}>
                        <td className="border px-3 py-1">{mat}</td>
                        <td className="border px-3 py-1 text-right">{len.toFixed(2)}</td>
                        <td className="border px-3 py-1 text-right">
                          {((len / (pipes.totalLength || 1)) * 100).toFixed(1)}%
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </fieldset>
      )}

      {/* Nodes Summary */}
      {nodes && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Nodos y Estructuras
          </legend>

          <div className="grid grid-cols-4 gap-4 text-center mb-4">
            <div className="bg-purple-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-purple-700">
                {nodes.manholes || 0}
              </div>
              <div className="text-xs text-gray-600">Cámaras de Inspección</div>
            </div>
            <div className="bg-purple-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-purple-700">
                {nodes.chambers || 0}
              </div>
              <div className="text-xs text-gray-600">Cámaras Especiales</div>
            </div>
            <div className="bg-purple-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-purple-700">
                {nodes.dropStructures || 0}
              </div>
              <div className="text-xs text-gray-600">Cámaras de Caída</div>
            </div>
            <div className="bg-purple-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-purple-700">
                {(nodes.manholes || 0) + (nodes.chambers || 0) + (nodes.dropStructures || 0)}
              </div>
              <div className="text-xs text-gray-600">Total Estructuras</div>
            </div>
          </div>

          {/* By Type Table */}
          {nodes.byType && Object.keys(nodes.byType).length > 0 && (
            <div>
              <h4 className="text-xs font-medium text-gray-600 mb-2">Por Tipo</h4>
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border px-3 py-1 text-left">Tipo</th>
                    <th className="border px-3 py-1 text-right">Cantidad</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(nodes.byType).map(([type, count]) => (
                    <tr key={type}>
                      <td className="border px-3 py-1">{type}</td>
                      <td className="border px-3 py-1 text-right">{count}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </fieldset>
      )}

      {/* Stormwater Summary */}
      {stormwater && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Aguas Lluvias
          </legend>

          <div className="grid grid-cols-4 gap-4 text-center mb-4">
            <div className="bg-cyan-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-cyan-700">
                {stormwater.inlets || 0}
              </div>
              <div className="text-xs text-gray-600">Sumideros</div>
            </div>
            <div className="bg-cyan-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-cyan-700">
                {stormwater.channels || 0}
              </div>
              <div className="text-xs text-gray-600">Canales</div>
            </div>
            <div className="bg-cyan-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-cyan-700">
                {stormwater.channelLength?.toFixed(1) || 0}
              </div>
              <div className="text-xs text-gray-600">Long. Canales (m)</div>
            </div>
            <div className="bg-cyan-50 p-3 rounded-lg">
              <div className="text-2xl font-bold text-cyan-700">
                {stormwater.detentionPonds || 0}
              </div>
              <div className="text-xs text-gray-600">Lagunas Retención</div>
            </div>
          </div>

          {stormwater.totalDetentionVolume !== undefined && stormwater.totalDetentionVolume > 0 && (
            <div className="bg-cyan-50 p-3 rounded-lg text-center">
              <div className="text-xl font-bold text-cyan-700">
                {stormwater.totalDetentionVolume.toFixed(1)} m³
              </div>
              <div className="text-xs text-gray-600">Volumen Total Retención</div>
            </div>
          )}

          {/* Inlets by Type */}
          {stormwater.byType && Object.keys(stormwater.byType).length > 0 && (
            <div className="mt-4">
              <h4 className="text-xs font-medium text-gray-600 mb-2">Sumideros por Tipo</h4>
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border px-3 py-1 text-left">Tipo</th>
                    <th className="border px-3 py-1 text-right">Cantidad</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(stormwater.byType).map(([type, count]) => (
                    <tr key={type}>
                      <td className="border px-3 py-1">{type}</td>
                      <td className="border px-3 py-1 text-right">{count}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </fieldset>
      )}

      {/* Quantities Summary Table */}
      {quantitiesSummary && quantitiesSummary.length > 0 && (
        <fieldset className="border rounded-lg p-4">
          <legend className="text-sm font-medium text-gray-700 px-2">
            Resumen de Cubicación
          </legend>

          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-gray-100">
                <th className="border px-3 py-2 text-left">Ítem</th>
                <th className="border px-3 py-2 text-left">Descripción</th>
                <th className="border px-3 py-2 text-right">Cantidad</th>
                <th className="border px-3 py-2 text-center">Unidad</th>
              </tr>
            </thead>
            <tbody>
              {quantitiesSummary.map((item, index) => (
                <tr key={index} className={index % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                  <td className="border px-3 py-2 font-mono">{item.item}</td>
                  <td className="border px-3 py-2">{item.description}</td>
                  <td className="border px-3 py-2 text-right font-mono">{item.quantity.toFixed(2)}</td>
                  <td className="border px-3 py-2 text-center">{item.unit}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <p className="mt-2 text-xs text-gray-500">
            * Cubicación preliminar generada automáticamente. Verificar con planos definitivos.
          </p>
        </fieldset>
      )}

      {/* Empty State */}
      {!pipes && !nodes && !stormwater && (
        <div className="text-center py-8 text-gray-500">
          <div className="text-4xl mb-2">📦</div>
          <p>No hay datos de infraestructura disponibles.</p>
          <p className="text-sm">Agregue tuberías, cámaras u otros elementos al proyecto.</p>
        </div>
      )}
    </div>
  );
}

export default InfrastructureSummaryDisplay;
