'use client';

/**
 * Population & Demand Editor Component
 *
 * Edits population projections and water/sewer demand calculations.
 * Includes Harmon factor, dotation, and flow calculations.
 */

import { useCallback } from 'react';
import type { PopulationDemandContent } from '@/types/documents';

interface PopulationDemandEditorProps {
  content: PopulationDemandContent;
  onChange: (content: PopulationDemandContent) => void;
  readOnly?: boolean;
}

export function PopulationDemandEditor({ content, onChange, readOnly = false }: PopulationDemandEditorProps) {
  const updateField = useCallback(<K extends keyof PopulationDemandContent>(
    field: K,
    value: PopulationDemandContent[K]
  ) => {
    if (readOnly) return;
    onChange({ ...content, [field]: value, autoGenerated: false });
  }, [content, onChange, readOnly]);

  const updateWaterDemand = useCallback((
    field: string,
    value: number | undefined
  ) => {
    if (readOnly) return;
    onChange({
      ...content,
      waterDemand: {
        ...content.waterDemand,
        [field]: value,
      },
      autoGenerated: false,
    });
  }, [content, onChange, readOnly]);

  const updateSewerFlow = useCallback((
    field: string,
    value: number | undefined
  ) => {
    if (readOnly) return;
    onChange({
      ...content,
      sewerFlow: {
        ...content.sewerFlow,
        [field]: value,
      },
      autoGenerated: false,
    });
  }, [content, onChange, readOnly]);

  // Calculate projected population based on growth rate
  const calculateProjectedPop = useCallback(() => {
    if (readOnly) return;
    const years = (content.projectedYear || new Date().getFullYear() + 20) - (content.currentYear || new Date().getFullYear());
    const projected = Math.round(
      (content.currentPopulation || 0) * Math.pow(1 + (content.growthRate || 1.5) / 100, years)
    );
    updateField('projectedPopulation', projected);
  }, [content, readOnly, updateField]);

  // Calculate Harmon factor
  const calculateHarmon = useCallback(() => {
    if (readOnly) return;
    const popThousands = (content.projectedPopulation || 0) / 1000;
    const harmon = 1 + 14 / (4 + Math.sqrt(popThousands));
    updateSewerFlow('harmonFactor', Math.round(harmon * 100) / 100);
  }, [content, readOnly, updateSewerFlow]);

  const wd = content.waterDemand || {};
  const sf = content.sewerFlow || {};

  return (
    <div className="population-demand-editor space-y-6">
      {/* Auto-generated indicator */}
      {content.autoGenerated && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
          <span className="text-sm text-blue-800">
            📊 Datos calculados automáticamente. Puedes modificarlos.
          </span>
        </div>
      )}

      {/* Current Population */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Población Actual
        </legend>

        <div className="grid grid-cols-3 gap-4">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Población (hab)</label>
            <input
              type="number"
              value={content.currentPopulation || ''}
              onChange={(e) => updateField('currentPopulation', parseInt(e.target.value) || 0)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Año Base</label>
            <input
              type="number"
              value={content.currentYear || new Date().getFullYear()}
              onChange={(e) => updateField('currentYear', parseInt(e.target.value) || new Date().getFullYear())}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Viviendas</label>
            <input
              type="number"
              value={content.currentHouseholds || ''}
              onChange={(e) => updateField('currentHouseholds', parseInt(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              placeholder="Opcional"
              disabled={readOnly}
            />
          </div>
        </div>
      </fieldset>

      {/* Population Projection */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Proyección de Población
        </legend>

        <div className="grid grid-cols-4 gap-4">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Tasa Crecimiento (%)</label>
            <input
              type="number"
              value={content.growthRate || ''}
              onChange={(e) => updateField('growthRate', parseFloat(e.target.value) || 0)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.1"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Año Proyección</label>
            <input
              type="number"
              value={content.projectedYear || ''}
              onChange={(e) => updateField('projectedYear', parseInt(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Población Proyectada</label>
            <div className="flex gap-1">
              <input
                type="number"
                value={content.projectedPopulation || ''}
                onChange={(e) => updateField('projectedPopulation', parseInt(e.target.value) || 0)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
              {!readOnly && (
                <button
                  type="button"
                  onClick={calculateProjectedPop}
                  className="px-2 py-1 text-xs bg-gray-100 border rounded hover:bg-gray-200"
                  title="Calcular automáticamente"
                >
                  ⟳
                </button>
              )}
            </div>
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Hab/Vivienda</label>
            <input
              type="number"
              value={content.averageOccupancy || ''}
              onChange={(e) => updateField('averageOccupancy', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.1"
              placeholder="4.0"
              disabled={readOnly}
            />
          </div>
        </div>

        {/* Population calculation formula display */}
        <div className="mt-3 p-2 bg-gray-50 rounded text-xs text-gray-600">
          <span className="font-mono">
            P<sub>f</sub> = P<sub>i</sub> × (1 + r)<sup>n</sup> = {content.currentPopulation || 'Pi'} × (1 + {(content.growthRate || 0) / 100})<sup>{(content.projectedYear || 0) - (content.currentYear || 0)}</sup> = {content.projectedPopulation || '?'} hab
          </span>
        </div>
      </fieldset>

      {/* Water Demand */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Demanda de Agua Potable
        </legend>

        <div className="grid grid-cols-4 gap-3">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Dotación (L/hab/día)</label>
            <input
              type="number"
              value={wd.dotation || ''}
              onChange={(e) => updateWaterDemand('dotation', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              placeholder="180"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Qmd (L/s)</label>
            <input
              type="number"
              value={wd.averageDailyDemand || ''}
              onChange={(e) => updateWaterDemand('averageDailyDemand', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">K1 (día máx)</label>
            <input
              type="number"
              value={wd.peakDayFactor || ''}
              onChange={(e) => updateWaterDemand('peakDayFactor', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.1"
              placeholder="1.5"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">K2 (hora máx)</label>
            <input
              type="number"
              value={wd.peakHourFactor || ''}
              onChange={(e) => updateWaterDemand('peakHourFactor', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.1"
              placeholder="1.5"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Qmáx día (L/s)</label>
            <input
              type="number"
              value={wd.maxDailyDemand || ''}
              onChange={(e) => updateWaterDemand('maxDailyDemand', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Qmáx hora (L/s)</label>
            <input
              type="number"
              value={wd.maxHourlyDemand || ''}
              onChange={(e) => updateWaterDemand('maxHourlyDemand', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              disabled={readOnly}
            />
          </div>
        </div>

        <div className="mt-3 p-2 bg-gray-50 rounded text-xs text-gray-600 space-y-1">
          <div><span className="font-mono">Qmd = (P × Dot) / 86400 = ({content.projectedPopulation || 'P'} × {wd.dotation || 180}) / 86400 L/s</span></div>
          <div><span className="font-mono">Qmáx día = Qmd × K1</span></div>
          <div><span className="font-mono">Qmáx hora = Qmd × K1 × K2</span></div>
        </div>
      </fieldset>

      {/* Sewer Flow */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Caudales de Alcantarillado
        </legend>

        <div className="grid grid-cols-4 gap-3">
          <div>
            <label className="block text-xs text-gray-500 mb-1">Coef. Retorno</label>
            <input
              type="number"
              value={sf.returnFactor || ''}
              onChange={(e) => updateSewerFlow('returnFactor', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.05"
              placeholder="0.80"
              min="0"
              max="1"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Qmed (L/s)</label>
            <input
              type="number"
              value={sf.averageFlow || ''}
              onChange={(e) => updateSewerFlow('averageFlow', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Factor Harmon (M)</label>
            <div className="flex gap-1">
              <input
                type="number"
                value={sf.harmonFactor || ''}
                onChange={(e) => updateSewerFlow('harmonFactor', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.01"
                disabled={readOnly}
              />
              {!readOnly && (
                <button
                  type="button"
                  onClick={calculateHarmon}
                  className="px-2 py-1 text-xs bg-gray-100 border rounded hover:bg-gray-200"
                  title="Calcular Factor Harmon"
                >
                  ⟳
                </button>
              )}
            </div>
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">Qmáx (L/s)</label>
            <input
              type="number"
              value={sf.peakFlow || ''}
              onChange={(e) => updateSewerFlow('peakFlow', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              disabled={readOnly}
            />
          </div>
          <div className="col-span-2">
            <label className="block text-xs text-gray-500 mb-1">Infiltración (L/s/ha)</label>
            <input
              type="number"
              value={sf.infiltration || ''}
              onChange={(e) => updateSewerFlow('infiltration', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              placeholder="0.1"
              disabled={readOnly}
            />
          </div>
          <div className="col-span-2">
            <label className="block text-xs text-gray-500 mb-1">Conexiones Erradas (L/s)</label>
            <input
              type="number"
              value={sf.erroneousConnections || ''}
              onChange={(e) => updateSewerFlow('erroneousConnections', parseFloat(e.target.value) || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              step="0.01"
              disabled={readOnly}
            />
          </div>
        </div>

        <div className="mt-3 p-2 bg-gray-50 rounded text-xs text-gray-600 space-y-1">
          <div><span className="font-mono">Qmed = (P × Dot × CR) / 86400</span></div>
          <div><span className="font-mono">M = 1 + 14 / (4 + √P) = 1 + 14 / (4 + √{(content.projectedPopulation || 0) / 1000}) = {sf.harmonFactor || '?'}</span></div>
          <div><span className="font-mono">Qmáx = Qmed × M + Qinf + Qce</span></div>
        </div>
      </fieldset>
    </div>
  );
}

export default PopulationDemandEditor;
