'use client';

/**
 * Study Area Editor Component
 *
 * Edits study area content for engineering documents.
 * Can be auto-populated from project data and manually refined.
 */

import { useCallback } from 'react';
import type { StudyAreaContent } from '@/types/documents';

interface StudyAreaEditorProps {
  content: StudyAreaContent;
  onChange: (content: StudyAreaContent) => void;
  readOnly?: boolean;
}

// Slope classification labels
const SLOPE_LABELS: Record<string, string> = {
  plano: 'Plano (< 2%)',
  suave: 'Suave (2-5%)',
  moderado: 'Moderado (5-15%)',
  fuerte: 'Fuerte (15-30%)',
  muy_fuerte: 'Muy Fuerte (> 30%)',
};

// Hydrologic group descriptions
const HYDRO_GROUP_LABELS: Record<string, string> = {
  A: 'A - Alta infiltración (arena)',
  B: 'B - Moderada infiltración (limo)',
  C: 'C - Baja infiltración (arcilla)',
  D: 'D - Muy baja infiltración (arcilla expansiva)',
};

export function StudyAreaEditor({ content, onChange, readOnly = false }: StudyAreaEditorProps) {
  const updateField = useCallback(<K extends keyof StudyAreaContent>(
    field: K,
    value: StudyAreaContent[K]
  ) => {
    if (readOnly) return;
    onChange({ ...content, [field]: value, autoGenerated: false });
  }, [content, onChange, readOnly]);

  const updateNestedField = useCallback(<
    K extends keyof StudyAreaContent,
    NK extends keyof NonNullable<StudyAreaContent[K]>
  >(
    field: K,
    nestedField: NK,
    value: unknown
  ) => {
    if (readOnly) return;
    const current = content[field] as Record<string, unknown> || {};
    onChange({
      ...content,
      [field]: { ...current, [nestedField]: value },
      autoGenerated: false,
    });
  }, [content, onChange, readOnly]);

  return (
    <div className="study-area-editor space-y-6">
      {/* Auto-generated indicator */}
      {content.autoGenerated && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
          <div className="flex items-center gap-2">
            <span className="text-blue-600 text-sm">⚙️</span>
            <span className="text-sm text-blue-800">
              Contenido generado automáticamente desde datos del proyecto.
              Puedes editarlo libremente.
            </span>
          </div>
        </div>
      )}

      {/* Description */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Descripción General
        </legend>
        <textarea
          value={content.description}
          onChange={(e) => updateField('description', e.target.value)}
          placeholder="Descripción general del área de estudio..."
          className="w-full h-24 px-3 py-2 text-sm border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          disabled={readOnly}
        />
      </fieldset>

      {/* Boundaries & Area */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Límites y Superficie
        </legend>

        <div className="space-y-4">
          {/* Boundaries grid */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Norte</label>
              <input
                type="text"
                value={content.boundaries.north}
                onChange={(e) => updateNestedField('boundaries', 'north', e.target.value)}
                placeholder="Límite norte"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Sur</label>
              <input
                type="text"
                value={content.boundaries.south}
                onChange={(e) => updateNestedField('boundaries', 'south', e.target.value)}
                placeholder="Límite sur"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Este</label>
              <input
                type="text"
                value={content.boundaries.east}
                onChange={(e) => updateNestedField('boundaries', 'east', e.target.value)}
                placeholder="Límite este"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Oeste</label>
              <input
                type="text"
                value={content.boundaries.west}
                onChange={(e) => updateNestedField('boundaries', 'west', e.target.value)}
                placeholder="Límite oeste"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
          </div>

          {/* Area metrics */}
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Área Total (ha)</label>
              <input
                type="number"
                value={content.totalArea || ''}
                onChange={(e) => updateField('totalArea', parseFloat(e.target.value) || 0)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.01"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Área Impermeable (ha)</label>
              <input
                type="number"
                value={content.imperviousArea || ''}
                onChange={(e) => updateField('imperviousArea', parseFloat(e.target.value) || 0)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.01"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Área Permeable (ha)</label>
              <input
                type="number"
                value={content.perviousArea || ''}
                onChange={(e) => updateField('perviousArea', parseFloat(e.target.value) || 0)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.01"
                disabled={readOnly}
              />
            </div>
          </div>
        </div>
      </fieldset>

      {/* Topography */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Topografía
        </legend>

        <div className="space-y-3">
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Cota Mín. (m.s.n.m.)</label>
              <input
                type="number"
                value={content.topography.minElevation || ''}
                onChange={(e) => updateNestedField('topography', 'minElevation', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Cota Máx. (m.s.n.m.)</label>
              <input
                type="number"
                value={content.topography.maxElevation || ''}
                onChange={(e) => updateNestedField('topography', 'maxElevation', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Pendiente Media (%)</label>
              <input
                type="number"
                value={content.topography.averageSlope || ''}
                onChange={(e) => updateNestedField('topography', 'averageSlope', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.1"
                disabled={readOnly}
              />
            </div>
          </div>

          <div>
            <label className="block text-xs text-gray-500 mb-1">Clasificación de Pendiente</label>
            <select
              value={content.topography.slopeClassification || ''}
              onChange={(e) => updateNestedField('topography', 'slopeClassification', e.target.value || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            >
              <option value="">Seleccionar...</option>
              {Object.entries(SLOPE_LABELS).map(([key, label]) => (
                <option key={key} value={key}>{label}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs text-gray-500 mb-1">Descripción del Terreno</label>
            <input
              type="text"
              value={content.topography.terrainDescription || ''}
              onChange={(e) => updateNestedField('topography', 'terrainDescription', e.target.value)}
              placeholder="Ej: Terreno ondulado con pendiente hacia el norte"
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
        </div>
      </fieldset>

      {/* Soils */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Suelos
        </legend>

        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Tipo Predominante</label>
              <input
                type="text"
                value={content.soils.predominantType || ''}
                onChange={(e) => updateNestedField('soils', 'predominantType', e.target.value)}
                placeholder="Ej: Arcilloso, Arenoso, Limoso"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Tasa Infiltración (mm/h)</label>
              <input
                type="number"
                value={content.soils.infiltrationRate || ''}
                onChange={(e) => updateNestedField('soils', 'infiltrationRate', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                step="0.1"
                disabled={readOnly}
              />
            </div>
          </div>

          <div>
            <label className="block text-xs text-gray-500 mb-1">Grupo Hidrológico (SCS)</label>
            <select
              value={content.soils.hydrologicGroup || ''}
              onChange={(e) => updateNestedField('soils', 'hydrologicGroup', e.target.value || undefined)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            >
              <option value="">Seleccionar...</option>
              {Object.entries(HYDRO_GROUP_LABELS).map(([key, label]) => (
                <option key={key} value={key}>{label}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs text-gray-500 mb-1">Descripción</label>
            <input
              type="text"
              value={content.soils.description || ''}
              onChange={(e) => updateNestedField('soils', 'description', e.target.value)}
              placeholder="Descripción adicional del suelo"
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
        </div>
      </fieldset>

      {/* Climate */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Clima y Pluviometría
        </legend>

        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Zona Climática</label>
              <input
                type="text"
                value={content.climate.climaticZone || ''}
                onChange={(e) => updateNestedField('climate', 'climaticZone', e.target.value)}
                placeholder="Ej: Templado mediterráneo"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Precipitación Anual (mm)</label>
              <input
                type="number"
                value={content.climate.annualRainfall || ''}
                onChange={(e) => updateNestedField('climate', 'annualRainfall', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Meses Lluviosos</label>
              <input
                type="text"
                value={content.climate.rainyMonths || ''}
                onChange={(e) => updateNestedField('climate', 'rainyMonths', e.target.value)}
                placeholder="Ej: Mayo a Agosto"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Estación IDF</label>
              <input
                type="text"
                value={content.climate.idfStation || ''}
                onChange={(e) => updateNestedField('climate', 'idfStation', e.target.value)}
                placeholder="Ej: Carriel Sur, Chillán"
                className="w-full px-2 py-1 text-sm border rounded"
                disabled={readOnly}
              />
            </div>
          </div>

          <div>
            <label className="block text-xs text-gray-500 mb-1">Fuente Datos IDF</label>
            <select
              value={content.climate.idfSource || ''}
              onChange={(e) => updateNestedField('climate', 'idfSource', e.target.value)}
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            >
              <option value="">Seleccionar...</option>
              <option value="DGA">DGA - Dirección General de Aguas</option>
              <option value="DMC">DMC - Dirección Meteorológica</option>
              <option value="MINVU">Manual MINVU Aguas Lluvias</option>
              <option value="MOP">MOP - Manual de Carreteras</option>
              <option value="otro">Otro</option>
            </select>
          </div>
        </div>
      </fieldset>

      {/* Land Use */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Uso de Suelo (%)
        </legend>

        <div className="space-y-3">
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Residencial</label>
              <input
                type="number"
                value={content.landUse.residential || ''}
                onChange={(e) => updateNestedField('landUse', 'residential', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                min="0"
                max="100"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Comercial</label>
              <input
                type="number"
                value={content.landUse.commercial || ''}
                onChange={(e) => updateNestedField('landUse', 'commercial', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                min="0"
                max="100"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Industrial</label>
              <input
                type="number"
                value={content.landUse.industrial || ''}
                onChange={(e) => updateNestedField('landUse', 'industrial', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                min="0"
                max="100"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Áreas Verdes</label>
              <input
                type="number"
                value={content.landUse.greenAreas || ''}
                onChange={(e) => updateNestedField('landUse', 'greenAreas', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                min="0"
                max="100"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Vialidad</label>
              <input
                type="number"
                value={content.landUse.roads || ''}
                onChange={(e) => updateNestedField('landUse', 'roads', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                min="0"
                max="100"
                disabled={readOnly}
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Otro</label>
              <input
                type="number"
                value={content.landUse.other || ''}
                onChange={(e) => updateNestedField('landUse', 'other', parseFloat(e.target.value) || undefined)}
                className="w-full px-2 py-1 text-sm border rounded"
                min="0"
                max="100"
                disabled={readOnly}
              />
            </div>
          </div>

          <div>
            <label className="block text-xs text-gray-500 mb-1">Descripción del Uso de Suelo</label>
            <input
              type="text"
              value={content.landUse.description || ''}
              onChange={(e) => updateNestedField('landUse', 'description', e.target.value)}
              placeholder="Descripción general del uso de suelo"
              className="w-full px-2 py-1 text-sm border rounded"
              disabled={readOnly}
            />
          </div>
        </div>
      </fieldset>

      {/* Map/Image Reference */}
      <fieldset className="border rounded-lg p-4">
        <legend className="text-sm font-medium text-gray-700 px-2">
          Imagen/Plano de Ubicación
        </legend>

        <div>
          <label className="block text-xs text-gray-500 mb-1">URL de Imagen</label>
          <input
            type="text"
            value={content.mapImageUrl || ''}
            onChange={(e) => updateField('mapImageUrl', e.target.value)}
            placeholder="URL de imagen o plano de ubicación"
            className="w-full px-2 py-1 text-sm border rounded"
            disabled={readOnly}
          />
        </div>

        {content.mapImageUrl && (
          <div className="mt-3">
            <img
              src={content.mapImageUrl}
              alt="Plano de ubicación"
              className="max-w-full h-auto rounded border"
            />
          </div>
        )}
      </fieldset>

      {/* Metadata */}
      {content.lastUpdated && (
        <p className="text-xs text-gray-400 text-right">
          Última actualización: {new Date(content.lastUpdated).toLocaleString('es-CL')}
        </p>
      )}
    </div>
  );
}

export default StudyAreaEditor;
