import { NextRequest, NextResponse } from 'next/server';
import { withAuth, AuthenticatedRequest } from '@/lib/auth-middleware';
import { getDb, query, queryOne, execute } from '@ledesign/db';
import { Project } from '@/types/user';
import type { Cubicacion, CubicacionItem, CubicacionSubtotal } from '@ledesign/cubicacion';
import { generateId } from '@/lib/utils';

export const dynamic = 'force-dynamic';

interface DbCubicacion {
  id: string;
  project_id: string;
  name: string;
  version: number;
  status: string;
  items_json: string;
  subtotals_json: string;
  grand_total: number;
  price_date: string | null;
  price_source: string | null;
  currency: string;
  uf_value: number | null;
  auto_generation_enabled: number;
  last_auto_generated: string | null;
  generator_config_json: string | null;
  approved_by: string | null;
  approval_date: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
}

function parseCubicacion(row: DbCubicacion): Cubicacion {
  return {
    id: row.id,
    projectId: row.project_id,
    name: row.name,
    version: row.version,
    status: row.status as Cubicacion['status'],
    items: JSON.parse(row.items_json || '[]') as CubicacionItem[],
    subtotals: JSON.parse(row.subtotals_json || '[]') as CubicacionSubtotal[],
    grandTotal: row.grand_total,
    priceDate: row.price_date || new Date().toISOString().split('T')[0],
    priceSource: row.price_source || 'SERVIU RM 2024',
    currency: row.currency as 'CLP' | 'UF',
    ufValue: row.uf_value || undefined,
    autoGenerationEnabled: row.auto_generation_enabled === 1,
    lastAutoGenerated: row.last_auto_generated || undefined,
    approvedBy: row.approved_by || undefined,
    approvalDate: row.approval_date || undefined,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// GET /api/projects/[id]/cubicacion - Get all cubicaciones for a project
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  return withAuth(request, async (req: AuthenticatedRequest) => {
    try {
      const { id } = await params;

      // Verify project ownership
      const project = await queryOne<Project>(
        getDb(),
        `SELECT id FROM projects WHERE id = ? AND user_id = ?`,
        [id, req.user.userId]
      );

      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        );
      }

      const cubicaciones = await query<DbCubicacion>(
        getDb(),
        `SELECT * FROM cubicaciones
         WHERE project_id = ?
         ORDER BY created_at DESC`,
        [id]
      );

      return NextResponse.json({
        success: true,
        cubicaciones: cubicaciones.map(parseCubicacion),
      });
    } catch (error) {
      console.error('Error fetching cubicaciones:', error);
      return NextResponse.json(
        { error: 'Failed to fetch cubicaciones' },
        { status: 500 }
      );
    }
  });
}

// POST /api/projects/[id]/cubicacion - Create new cubicacion
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  return withAuth(request, async (req: AuthenticatedRequest) => {
    try {
      const { id } = await params;
      const body = await request.json();

      // Verify project ownership
      const project = await queryOne<Project>(
        getDb(),
        `SELECT id FROM projects WHERE id = ? AND user_id = ?`,
        [id, req.user.userId]
      );

      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        );
      }

      const now = new Date().toISOString();
      const cubicacionId = body.id || generateId();

      const cubicacion: Cubicacion = {
        id: cubicacionId,
        projectId: id,
        name: body.name || `Cubicación ${new Date().toLocaleDateString('es-CL')}`,
        version: body.version || 1,
        status: body.status || 'draft',
        items: body.items || [],
        subtotals: body.subtotals || [],
        grandTotal: body.grandTotal || 0,
        priceDate: body.priceDate || now.split('T')[0],
        priceSource: body.priceSource || 'SERVIU RM 2024',
        currency: body.currency || 'CLP',
        ufValue: body.ufValue,
        autoGenerationEnabled: body.autoGenerationEnabled ?? true,
        lastAutoGenerated: body.lastAutoGenerated,
        createdAt: now,
        updatedAt: now,
      };

      await execute(
        getDb(),
        `INSERT INTO cubicaciones (
          id, project_id, name, version, status,
          items_json, subtotals_json, grand_total,
          price_date, price_source, currency, uf_value,
          auto_generation_enabled, last_auto_generated,
          created_at, updated_at, created_by
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          cubicacion.id,
          id,
          cubicacion.name,
          cubicacion.version,
          cubicacion.status,
          JSON.stringify(cubicacion.items),
          JSON.stringify(cubicacion.subtotals),
          cubicacion.grandTotal,
          cubicacion.priceDate,
          cubicacion.priceSource,
          cubicacion.currency,
          cubicacion.ufValue || null,
          cubicacion.autoGenerationEnabled ? 1 : 0,
          cubicacion.lastAutoGenerated || null,
          now,
          now,
          req.user.userId,
        ]
      );

      // Update project timestamp
      await execute(
        getDb(),
        `UPDATE projects SET updated_at = ? WHERE id = ?`,
        [now, id]
      );

      return NextResponse.json({
        success: true,
        cubicacion,
      });
    } catch (error) {
      console.error('Error creating cubicacion:', error);
      return NextResponse.json(
        { error: 'Failed to create cubicación' },
        { status: 500 }
      );
    }
  });
}

// PUT /api/projects/[id]/cubicacion - Update cubicacion
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  return withAuth(request, async (req: AuthenticatedRequest) => {
    try {
      const { id: projectId } = await params;
      const body = await request.json();
      const { id: cubicacionId, ...updates } = body;

      if (!cubicacionId) {
        return NextResponse.json(
          { error: 'Cubicación ID is required' },
          { status: 400 }
        );
      }

      // Verify project ownership
      const project = await queryOne<Project>(
        getDb(),
        `SELECT id FROM projects WHERE id = ? AND user_id = ?`,
        [projectId, req.user.userId]
      );

      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        );
      }

      // Verify cubicacion exists
      const existing = await queryOne<DbCubicacion>(
        getDb(),
        `SELECT id FROM cubicaciones WHERE id = ? AND project_id = ?`,
        [cubicacionId, projectId]
      );

      if (!existing) {
        return NextResponse.json(
          { error: 'Cubicación not found' },
          { status: 404 }
        );
      }

      const now = new Date().toISOString();
      const updateFields: string[] = ['updated_at = ?'];
      const updateValues: (string | number | boolean | null)[] = [now];

      if (updates.name !== undefined) {
        updateFields.push('name = ?');
        updateValues.push(updates.name);
      }
      if (updates.version !== undefined) {
        updateFields.push('version = ?');
        updateValues.push(updates.version);
      }
      if (updates.status !== undefined) {
        updateFields.push('status = ?');
        updateValues.push(updates.status);
      }
      if (updates.items !== undefined) {
        updateFields.push('items_json = ?');
        updateValues.push(JSON.stringify(updates.items));
      }
      if (updates.subtotals !== undefined) {
        updateFields.push('subtotals_json = ?');
        updateValues.push(JSON.stringify(updates.subtotals));
      }
      if (updates.grandTotal !== undefined) {
        updateFields.push('grand_total = ?');
        updateValues.push(updates.grandTotal);
      }
      if (updates.priceDate !== undefined) {
        updateFields.push('price_date = ?');
        updateValues.push(updates.priceDate);
      }
      if (updates.priceSource !== undefined) {
        updateFields.push('price_source = ?');
        updateValues.push(updates.priceSource);
      }
      if (updates.currency !== undefined) {
        updateFields.push('currency = ?');
        updateValues.push(updates.currency);
      }
      if (updates.ufValue !== undefined) {
        updateFields.push('uf_value = ?');
        updateValues.push(updates.ufValue);
      }
      if (updates.autoGenerationEnabled !== undefined) {
        updateFields.push('auto_generation_enabled = ?');
        updateValues.push(updates.autoGenerationEnabled ? 1 : 0);
      }
      if (updates.lastAutoGenerated !== undefined) {
        updateFields.push('last_auto_generated = ?');
        updateValues.push(updates.lastAutoGenerated);
      }
      if (updates.approvedBy !== undefined) {
        updateFields.push('approved_by = ?');
        updateValues.push(updates.approvedBy);
      }
      if (updates.approvalDate !== undefined) {
        updateFields.push('approval_date = ?');
        updateValues.push(updates.approvalDate);
      }

      updateValues.push(cubicacionId);

      await execute(
        getDb(),
        `UPDATE cubicaciones SET ${updateFields.join(', ')} WHERE id = ?`,
        updateValues
      );

      // Update project timestamp
      await execute(
        getDb(),
        `UPDATE projects SET updated_at = ? WHERE id = ?`,
        [now, projectId]
      );

      // Fetch updated cubicacion
      const updated = await queryOne<DbCubicacion>(
        getDb(),
        `SELECT * FROM cubicaciones WHERE id = ?`,
        [cubicacionId]
      );

      return NextResponse.json({
        success: true,
        cubicacion: updated ? parseCubicacion(updated) : null,
      });
    } catch (error) {
      console.error('Error updating cubicacion:', error);
      return NextResponse.json(
        { error: 'Failed to update cubicación' },
        { status: 500 }
      );
    }
  });
}

// DELETE /api/projects/[id]/cubicacion - Delete cubicacion
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  return withAuth(request, async (req: AuthenticatedRequest) => {
    try {
      const { id: projectId } = await params;
      const { searchParams } = new URL(request.url);
      const cubicacionId = searchParams.get('id');

      if (!cubicacionId) {
        return NextResponse.json(
          { error: 'Cubicación ID is required' },
          { status: 400 }
        );
      }

      // Verify project ownership
      const project = await queryOne<Project>(
        getDb(),
        `SELECT id FROM projects WHERE id = ? AND user_id = ?`,
        [projectId, req.user.userId]
      );

      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        );
      }

      // Hard delete
      await execute(
        getDb(),
        `DELETE FROM cubicaciones WHERE id = ? AND project_id = ?`,
        [cubicacionId, projectId]
      );

      return NextResponse.json({
        success: true,
        message: 'Cubicación deleted',
      });
    } catch (error) {
      console.error('Error deleting cubicacion:', error);
      return NextResponse.json(
        { error: 'Failed to delete cubicación' },
        { status: 500 }
      );
    }
  });
}
