/**
 * Document Templates
 *
 * Predefined templates for Chilean engineering documents.
 * Each template defines the standard sections for that document type.
 * Sections can be auto-populated from project data.
 */

import { generateId } from '@/lib/utils';
import type {
  DocumentTemplate,
  DocumentSection,
  DocumentType,
  SectionType,
  DocumentCaratula,
  StudyAreaContent,
  DesignCriteriaContent,
  PopulationDemandContent,
  InfrastructureSummaryContent,
  TextContent,
  ReferenceContent,
  TableContent,
  CalculationContent,
} from '@/types/documents';

// ============================================================================
// Template Section Generators
// ============================================================================

/**
 * Creates a text section
 */
function createTextSection(
  number: string,
  title: string,
  html: string = ''
): DocumentSection {
  return {
    id: generateId(),
    number,
    title,
    type: 'text',
    content: { type: 'text', html } as TextContent,
  };
}

/**
 * Creates a study area section (auto-populated)
 */
function createStudyAreaSection(number: string): DocumentSection {
  return {
    id: generateId(),
    number,
    title: 'Área de Estudio',
    type: 'study_area',
    content: {
      type: 'study_area',
      description: '',
      boundaries: { north: '', south: '', east: '', west: '' },
      totalArea: 0,
      topography: {},
      soils: {},
      climate: {},
      landUse: {},
      autoGenerated: true,
    } as StudyAreaContent,
  };
}

/**
 * Creates a design criteria section
 */
function createDesignCriteriaSection(
  number: string,
  projectType: DesignCriteriaContent['projectType'] = 'alcantarillado'
): DocumentSection {
  return {
    id: generateId(),
    number,
    title: 'Criterios de Diseño',
    type: 'design_criteria',
    content: {
      type: 'design_criteria',
      projectType,
      designPeriod: 20,
      designHorizon: `${new Date().getFullYear()}-${new Date().getFullYear() + 20}`,
      applicableNorms: [],
      autoGenerated: true,
    } as DesignCriteriaContent,
  };
}

/**
 * Creates a population & demand section
 */
function createPopulationDemandSection(number: string): DocumentSection {
  return {
    id: generateId(),
    number,
    title: 'Población y Demanda',
    type: 'population_demand',
    content: {
      type: 'population_demand',
      currentPopulation: 0,
      currentYear: new Date().getFullYear(),
      projectedPopulation: 0,
      projectedYear: new Date().getFullYear() + 20,
      growthRate: 1.5,
      autoGenerated: true,
    } as PopulationDemandContent,
  };
}

/**
 * Creates an infrastructure summary section
 */
function createInfrastructureSummarySection(number: string): DocumentSection {
  return {
    id: generateId(),
    number,
    title: 'Resumen de Infraestructura',
    type: 'infrastructure_summary',
    content: {
      type: 'infrastructure_summary',
      autoGenerated: true,
    } as InfrastructureSummaryContent,
  };
}

/**
 * Creates a reference section
 */
function createReferenceSection(number: string): DocumentSection {
  return {
    id: generateId(),
    number,
    title: 'Referencias Normativas',
    type: 'reference',
    content: {
      type: 'reference',
      references: [
        { code: 'NCh 1105', title: 'Ingeniería Sanitaria - Alcantarillado de aguas residuales' },
        { code: 'RIDAA', title: 'Reglamento de Instalaciones Domiciliarias de Agua Potable y Alcantarillado' },
        { code: 'NCh 691', title: 'Agua potable - Conducción, regulación y distribución' },
      ],
    } as ReferenceContent,
  };
}

/**
 * Creates a calculation section placeholder
 */
function createCalculationSection(
  number: string,
  title: string,
  calculationType: string
): DocumentSection {
  return {
    id: generateId(),
    number,
    title,
    type: 'calculation',
    content: {
      type: 'calculation',
      calculationType,
      inputs: {},
      results: {},
    } as CalculationContent,
  };
}

/**
 * Creates a table section
 */
function createTableSection(
  number: string,
  title: string,
  headers: string[] = [],
  caption?: string
): DocumentSection {
  return {
    id: generateId(),
    number,
    title,
    type: 'table',
    content: {
      type: 'table',
      headers,
      rows: [],
      caption,
    } as TableContent,
  };
}

// ============================================================================
// Document Templates
// ============================================================================

/**
 * Memoria de Cálculo Template
 * Complete calculation report for Chilean engineering projects
 */
export const MEMORIA_CALCULO_TEMPLATE: DocumentTemplate = {
  id: 'memoria-calculo-standard',
  name: 'Memoria de Cálculo Estándar',
  type: 'memoria_calculo',
  description: 'Plantilla estándar para memorias de cálculo de proyectos sanitarios',
  isSystem: true,
  createdAt: new Date().toISOString(),
  sections: [
    // 1. Introduction
    createTextSection('1', 'Introducción', '<p>La presente Memoria de Cálculo tiene por objetivo presentar los cálculos y diseños hidráulicos del proyecto.</p>'),

    // 2. Study Area (auto-populated)
    createStudyAreaSection('2'),

    // 3. Design Criteria
    createDesignCriteriaSection('3', 'alcantarillado'),

    // 4. Population & Demand (auto-populated)
    createPopulationDemandSection('4'),

    // 5. Hydraulic Calculations
    {
      id: generateId(),
      number: '5',
      title: 'Cálculos Hidráulicos',
      type: 'text',
      content: { type: 'text', html: '<p>A continuación se presentan los cálculos hidráulicos del proyecto.</p>' } as TextContent,
      subsections: [
        createCalculationSection('5.1', 'Cálculo de Caudales', 'harmon_factor'),
        createCalculationSection('5.2', 'Verificación de Tuberías (Manning)', 'manning_flow'),
        createCalculationSection('5.3', 'Pérdida de Carga', 'hazen_williams'),
      ],
    },

    // 6. Infrastructure Summary (auto-populated)
    createInfrastructureSummarySection('6'),

    // 7. Results Table
    createTableSection('7', 'Tabla de Resultados',
      ['Tramo', 'Diámetro (mm)', 'Pendiente (%)', 'Caudal (L/s)', 'Velocidad (m/s)', 'Verificación'],
      'Resumen de verificación hidráulica por tramo'
    ),

    // 8. Normative References
    createReferenceSection('8'),

    // 9. Conclusions
    createTextSection('9', 'Conclusiones', '<p>Se concluye que el diseño cumple con las normas aplicables.</p>'),
  ],
};

/**
 * Especificaciones Técnicas Template
 */
export const ESPECIFICACIONES_TECNICAS_TEMPLATE: DocumentTemplate = {
  id: 'eett-standard',
  name: 'Especificaciones Técnicas Estándar',
  type: 'especificaciones',
  description: 'Plantilla estándar para especificaciones técnicas de obras sanitarias',
  isSystem: true,
  createdAt: new Date().toISOString(),
  sections: [
    // 1. General
    createTextSection('1', 'Generalidades', '<p>Las presentes Especificaciones Técnicas establecen las condiciones mínimas que deberán cumplir los materiales y procedimientos constructivos.</p>'),

    // 2. Project Scope
    createTextSection('2', 'Alcance del Proyecto'),

    // 3. Applicable Norms
    createReferenceSection('3'),

    // 4. Material Specifications
    {
      id: generateId(),
      number: '4',
      title: 'Especificaciones de Materiales',
      type: 'text',
      content: { type: 'text', html: '' } as TextContent,
      subsections: [
        createTextSection('4.1', 'Tuberías', '<p>Las tuberías deberán cumplir con las siguientes especificaciones:</p>'),
        createTextSection('4.2', 'Cámaras de Inspección', '<p>Las cámaras de inspección serán prefabricadas o construidas in situ según lo indicado en planos.</p>'),
        createTextSection('4.3', 'Hormigones', '<p>Los hormigones deberán cumplir con NCh 170.</p>'),
      ],
    },

    // 5. Construction Methods
    {
      id: generateId(),
      number: '5',
      title: 'Procedimientos Constructivos',
      type: 'text',
      content: { type: 'text', html: '' } as TextContent,
      subsections: [
        createTextSection('5.1', 'Excavaciones', '<p>Las excavaciones se realizarán según las dimensiones indicadas en planos.</p>'),
        createTextSection('5.2', 'Instalación de Tuberías'),
        createTextSection('5.3', 'Rellenos'),
        createTextSection('5.4', 'Pruebas y Ensayos'),
      ],
    },

    // 6. Quality Control
    createTextSection('6', 'Control de Calidad', '<p>El contratista deberá implementar un plan de control de calidad que incluya:</p>'),

    // 7. Safety
    createTextSection('7', 'Seguridad y Medio Ambiente'),
  ],
};

/**
 * Informe Técnico Template
 */
export const INFORME_TECNICO_TEMPLATE: DocumentTemplate = {
  id: 'informe-tecnico-standard',
  name: 'Informe Técnico Estándar',
  type: 'informe_tecnico',
  description: 'Plantilla estándar para informes técnicos de proyectos de ingeniería',
  isSystem: true,
  createdAt: new Date().toISOString(),
  sections: [
    // 1. Executive Summary
    createTextSection('1', 'Resumen Ejecutivo'),

    // 2. Introduction
    createTextSection('2', 'Introducción', '<p>El presente informe técnico describe las características del proyecto.</p>'),

    // 3. Study Area
    createStudyAreaSection('3'),

    // 4. Project Description
    createTextSection('4', 'Descripción del Proyecto'),

    // 5. Infrastructure Inventory
    createInfrastructureSummarySection('5'),

    // 6. Design Summary
    {
      id: generateId(),
      number: '6',
      title: 'Resumen del Diseño',
      type: 'text',
      content: { type: 'text', html: '' } as TextContent,
      subsections: [
        createTextSection('6.1', 'Parámetros de Diseño'),
        createTextSection('6.2', 'Solución Adoptada'),
        createTextSection('6.3', 'Verificaciones Técnicas'),
      ],
    },

    // 7. Results Table
    createTableSection('7', 'Resumen de Resultados',
      ['Parámetro', 'Valor', 'Unidad', 'Norma', 'Estado'],
      'Resumen de verificaciones técnicas'
    ),

    // 8. Recommendations
    createTextSection('8', 'Recomendaciones'),

    // 9. Conclusions
    createTextSection('9', 'Conclusiones'),

    // 10. Annexes reference
    createTextSection('10', 'Anexos', '<p>Se adjuntan los siguientes anexos:</p><ul><li>Anexo A: Planos</li><li>Anexo B: Cálculos Detallados</li></ul>'),
  ],
};

/**
 * Presupuesto Template
 */
export const PRESUPUESTO_TEMPLATE: DocumentTemplate = {
  id: 'presupuesto-standard',
  name: 'Presupuesto Estándar',
  type: 'presupuesto',
  description: 'Plantilla estándar para presupuestos de obras sanitarias según itemizado SERVIU',
  isSystem: true,
  createdAt: new Date().toISOString(),
  sections: [
    // 1. General Information
    createTextSection('1', 'Antecedentes Generales'),

    // 2. Infrastructure Summary (for quantities reference)
    createInfrastructureSummarySection('2'),

    // 3. Budget by Category
    {
      id: generateId(),
      number: '3',
      title: 'Presupuesto Detallado',
      type: 'text',
      content: { type: 'text', html: '' } as TextContent,
      subsections: [
        createTableSection('3.1', 'Obras Preliminares',
          ['Item', 'Descripción', 'Unidad', 'Cantidad', 'P.U.', 'Total'],
          'Partida 1: Obras Preliminares'
        ),
        createTableSection('3.2', 'Movimiento de Tierras',
          ['Item', 'Descripción', 'Unidad', 'Cantidad', 'P.U.', 'Total'],
          'Partida 2: Movimiento de Tierras'
        ),
        createTableSection('3.3', 'Tuberías',
          ['Item', 'Descripción', 'Unidad', 'Cantidad', 'P.U.', 'Total'],
          'Partida 3: Tuberías y Accesorios'
        ),
        createTableSection('3.4', 'Cámaras',
          ['Item', 'Descripción', 'Unidad', 'Cantidad', 'P.U.', 'Total'],
          'Partida 4: Cámaras de Inspección'
        ),
        createTableSection('3.5', 'Reposiciones',
          ['Item', 'Descripción', 'Unidad', 'Cantidad', 'P.U.', 'Total'],
          'Partida 5: Reposiciones'
        ),
      ],
    },

    // 4. Summary
    createTableSection('4', 'Resumen del Presupuesto',
      ['Partida', 'Descripción', 'Subtotal'],
      'Resumen por partidas'
    ),

    // 5. Notes
    createTextSection('5', 'Notas', '<p>1. Los precios unitarios incluyen mano de obra, materiales, equipos y gastos generales.</p><p>2. Precios referenciados al itemizado SERVIU vigente.</p>'),
  ],
};

// ============================================================================
// Template Registry
// ============================================================================

/**
 * All available templates
 */
export const DOCUMENT_TEMPLATES: Record<DocumentType, DocumentTemplate> = {
  memoria_calculo: MEMORIA_CALCULO_TEMPLATE,
  especificaciones: ESPECIFICACIONES_TECNICAS_TEMPLATE,
  informe_tecnico: INFORME_TECNICO_TEMPLATE,
  presupuesto: PRESUPUESTO_TEMPLATE,
};

/**
 * Get template by document type
 */
export function getTemplateByType(type: DocumentType): DocumentTemplate {
  return DOCUMENT_TEMPLATES[type];
}

/**
 * Get all templates
 */
export function getAllTemplates(): DocumentTemplate[] {
  return Object.values(DOCUMENT_TEMPLATES);
}

/**
 * Clone a template with fresh IDs
 */
export function cloneTemplate(template: DocumentTemplate): DocumentSection[] {
  const cloneSections = (sections: DocumentSection[]): DocumentSection[] => {
    return sections.map((section) => ({
      ...section,
      id: generateId(),
      content: { ...section.content },
      subsections: section.subsections ? cloneSections(section.subsections) : undefined,
    }));
  };

  return cloneSections(template.sections);
}

/**
 * Default carátula values
 */
export const DEFAULT_CARATULA_BY_TYPE: Record<DocumentType, Partial<DocumentCaratula>> = {
  memoria_calculo: {
    revisionNumber: 0,
  },
  especificaciones: {
    revisionNumber: 0,
  },
  informe_tecnico: {
    revisionNumber: 0,
  },
  presupuesto: {
    revisionNumber: 0,
  },
};
