/**
 * Import verification criteria from SERVIU inspection checklists
 * Run with: npx tsx scripts/import-verification-criteria.ts
 *
 * Data extracted from:
 * - Check_List_Inspeccion.pdf
 * - Check_List_Inicio_de_Obras.pdf
 * - Check_List_Funcionamiento_del_Sistema_de_Aguas_Lluvias.pdf
 * - ChecklistRecepcionDefinitiva.pdf
 */

import { createClient } from '@libsql/client';

interface VerificationCriterion {
  code: string;
  category: string;
  subcategory: string | null;
  phase: string; // 'pre_construction', 'during', 'final_reception'
  description_es: string;
  measurement_type: string | null;
  pass_condition: string | null;
  min_value: number | null;
  max_value: number | null;
  tolerance: number | null;
  unit: string | null;
  severity: string; // 'critical', 'major', 'minor'
  reference_standard: string | null;
  requires_photo: boolean;
  requires_lab_test: boolean;
  test_method: string | null;
}

// Verification criteria extracted from SERVIU inspection checklists
const verificationCriteria: VerificationCriterion[] = [
  // === PRE-CONSTRUCTION ===
  {
    code: 'PRE-001',
    category: 'documentation',
    subcategory: 'plans',
    phase: 'pre_construction',
    description_es: 'Verificar que las copias de Planos adjuntas y el Informe Favorable sean la versión aprobada del Sistema PAVEL',
    measurement_type: 'visual',
    pass_condition: 'Planos coinciden con versión aprobada en PAVEL',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'Sistema PAVEL',
    requires_photo: false,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'PRE-002',
    category: 'documentation',
    subcategory: 'inspection_book',
    phase: 'pre_construction',
    description_es: 'Realizar apertura del Libro de Inspección Digital con la Nota Estándar de Inspección',
    measurement_type: 'administrative',
    pass_condition: 'Libro de inspección digital abierto',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: null,
    requires_photo: false,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'PRE-003',
    category: 'signage',
    subcategory: null,
    phase: 'pre_construction',
    description_es: 'Letrero Fiscalización SERVIU instalado en obra',
    measurement_type: 'visual',
    pass_condition: 'Letrero visible y legible',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'major',
    reference_standard: null,
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },

  // === STORMWATER (AGUAS LLUVIAS) - COLLECTORS ===
  {
    code: 'ALL-001',
    category: 'stormwater',
    subcategory: 'collector_trenches',
    phase: 'during',
    description_es: 'Sello de Fundación para colectores de aguas lluvias',
    measurement_type: 'visual',
    pass_condition: 'Sello adecuado sin material suelto',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'ALL-002',
    category: 'stormwater',
    subcategory: 'collector_trenches',
    phase: 'during',
    description_es: 'Relleno tipo 3 (base del tubo): arena fina con porcentaje que pasa malla Nº 200 ≤10%, espesor de capa entre 5 y 10 cm',
    measurement_type: 'measurement',
    pass_condition: 'Pasante malla 200 ≤ 10%, espesor 5-10 cm',
    min_value: 5,
    max_value: 10,
    tolerance: null,
    unit: 'cm',
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: true,
    test_method: 'Granulometría',
  },
  {
    code: 'ALL-003',
    category: 'stormwater',
    subcategory: 'collector_trenches',
    phase: 'during',
    description_es: 'Relleno tipo 2 (entre base del tubo y 30 cm sobre la clave): material ≤ 1/2" (12,5 mm)',
    measurement_type: 'measurement',
    pass_condition: 'Tamaño máximo ≤ 12.5 mm',
    min_value: null,
    max_value: 12.5,
    tolerance: null,
    unit: 'mm',
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'ALL-004',
    category: 'stormwater',
    subcategory: 'collector_trenches',
    phase: 'during',
    description_es: 'Relleno tipo 1 (30 cm sobre la base del tubo): material ≤ 2" libre de basura, escombros y materia orgánica',
    measurement_type: 'measurement',
    pass_condition: 'Tamaño máximo ≤ 50 mm, libre de contaminantes',
    min_value: null,
    max_value: 50,
    tolerance: null,
    unit: 'mm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'ALL-005',
    category: 'stormwater',
    subcategory: 'collector_trenches',
    phase: 'during',
    description_es: 'Compactación de rellenos granulares en zanjas de colectores',
    measurement_type: 'test',
    pass_condition: '≥ 95% Proctor Modificado o ≥ 80% Densidad Relativa',
    min_value: 95,
    max_value: null,
    tolerance: null,
    unit: '%PM',
    severity: 'critical',
    reference_standard: 'NCh 1515',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Densidad in-situ',
  },
  {
    code: 'ALL-006',
    category: 'stormwater',
    subcategory: 'collector_trenches',
    phase: 'during',
    description_es: 'Frecuencia de control de compactación: un control por capa entre cámaras o uno por cada 50 m/l',
    measurement_type: 'frequency',
    pass_condition: '1 control/capa entre cámaras o 1/50m',
    min_value: null,
    max_value: 50,
    tolerance: null,
    unit: 'm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Densidad in-situ',
  },

  // === STORMWATER - INFILTRATION TRENCHES ===
  {
    code: 'ALL-010',
    category: 'stormwater',
    subcategory: 'infiltration_trenches',
    phase: 'during',
    description_es: 'Porchet real ≥ al de proyecto para zanjas de infiltración',
    measurement_type: 'test',
    pass_condition: 'Porchet medido ≥ Porchet diseño',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: 'mm/h',
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Ensayo Porchet',
  },
  {
    code: 'ALL-011',
    category: 'stormwater',
    subcategory: 'infiltration_trenches',
    phase: 'during',
    description_es: 'Tubería ranurada de fábrica - solicitar ficha técnica y guías de despacho',
    measurement_type: 'documentation',
    pass_condition: 'Ficha técnica y guías de despacho disponibles',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'ALL-012',
    category: 'stormwater',
    subcategory: 'infiltration_trenches',
    phase: 'during',
    description_es: 'Relleno tipo 3 (base del tubo) en zanja de infiltración: gravilla, espesor 5-10 cm',
    measurement_type: 'measurement',
    pass_condition: 'Gravilla, espesor 5-10 cm',
    min_value: 5,
    max_value: 10,
    tolerance: null,
    unit: 'cm',
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'ALL-013',
    category: 'stormwater',
    subcategory: 'infiltration_trenches',
    phase: 'during',
    description_es: 'Set fotográfico de secuencia constructiva de zanjas de infiltración',
    measurement_type: 'documentation',
    pass_condition: 'Registro fotográfico completo',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },

  // === STRUCTURAL PACKAGE - SUBGRADE ===
  {
    code: 'PAV-001',
    category: 'pavement',
    subcategory: 'subgrade',
    phase: 'during',
    description_es: 'CBR de sub-rasante debe ser mayor o igual al CBR de diseño',
    measurement_type: 'test',
    pass_condition: 'CBR medido ≥ CBR diseño',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1534',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'CBR',
  },
  {
    code: 'PAV-002',
    category: 'pavement',
    subcategory: 'subgrade',
    phase: 'during',
    description_es: 'Índice de Plasticidad de sub-rasante < 10%',
    measurement_type: 'test',
    pass_condition: 'IP < 10%',
    min_value: null,
    max_value: 10,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1517',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Límites de Atterberg',
  },
  {
    code: 'PAV-003',
    category: 'pavement',
    subcategory: 'subgrade',
    phase: 'during',
    description_es: 'Compactación de sub-rasante ≥ 95% Proctor Modificado',
    measurement_type: 'test',
    pass_condition: 'Compactación ≥ 95% PM',
    min_value: 95,
    max_value: null,
    tolerance: null,
    unit: '%PM',
    severity: 'critical',
    reference_standard: 'NCh 1515',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Densidad in-situ',
  },

  // === STRUCTURAL PACKAGE - IMPROVEMENT LAYER ===
  {
    code: 'PAV-010',
    category: 'pavement',
    subcategory: 'improvement',
    phase: 'during',
    description_es: 'CBR de mejoramiento debe ser mayor o igual al CBR de proyecto',
    measurement_type: 'test',
    pass_condition: 'CBR medido ≥ CBR proyecto',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1534',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'CBR',
  },
  {
    code: 'PAV-011',
    category: 'pavement',
    subcategory: 'improvement',
    phase: 'during',
    description_es: 'Índice de Plasticidad de mejoramiento < 10%',
    measurement_type: 'test',
    pass_condition: 'IP < 10%',
    min_value: null,
    max_value: 10,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1517',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Límites de Atterberg',
  },
  {
    code: 'PAV-012',
    category: 'pavement',
    subcategory: 'improvement',
    phase: 'during',
    description_es: 'Espesor de capa de mejoramiento según diseño',
    measurement_type: 'measurement',
    pass_condition: 'Espesor = Espesor diseño ± tolerancia',
    min_value: null,
    max_value: null,
    tolerance: 1,
    unit: 'cm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-013',
    category: 'pavement',
    subcategory: 'improvement',
    phase: 'during',
    description_es: 'Compactación de mejoramiento ≥ 95% Proctor Modificado',
    measurement_type: 'test',
    pass_condition: 'Compactación ≥ 95% PM',
    min_value: 95,
    max_value: null,
    tolerance: null,
    unit: '%PM',
    severity: 'critical',
    reference_standard: 'NCh 1515',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Densidad in-situ',
  },

  // === STRUCTURAL PACKAGE - SUB-BASE ===
  {
    code: 'PAV-020',
    category: 'pavement',
    subcategory: 'subbase',
    phase: 'during',
    description_es: 'CBR de sub-base debe ser mayor o igual al CBR de proyecto',
    measurement_type: 'test',
    pass_condition: 'CBR medido ≥ CBR proyecto',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1534',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'CBR',
  },
  {
    code: 'PAV-021',
    category: 'pavement',
    subcategory: 'subbase',
    phase: 'during',
    description_es: 'Índice de Plasticidad de sub-base < 8%',
    measurement_type: 'test',
    pass_condition: 'IP < 8%',
    min_value: null,
    max_value: 8,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1517',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Límites de Atterberg',
  },
  {
    code: 'PAV-022',
    category: 'pavement',
    subcategory: 'subbase',
    phase: 'during',
    description_es: 'Espesor de capa de sub-base según diseño',
    measurement_type: 'measurement',
    pass_condition: 'Espesor = Espesor diseño ± tolerancia',
    min_value: null,
    max_value: null,
    tolerance: 1,
    unit: 'cm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-023',
    category: 'pavement',
    subcategory: 'subbase',
    phase: 'during',
    description_es: 'Compactación de sub-base ≥ 95% Proctor Modificado',
    measurement_type: 'test',
    pass_condition: 'Compactación ≥ 95% PM',
    min_value: 95,
    max_value: null,
    tolerance: null,
    unit: '%PM',
    severity: 'critical',
    reference_standard: 'NCh 1515',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Densidad in-situ',
  },

  // === STRUCTURAL PACKAGE - BASE ===
  {
    code: 'PAV-030',
    category: 'pavement',
    subcategory: 'base',
    phase: 'during',
    description_es: 'CBR de base debe ser mayor o igual al CBR de proyecto',
    measurement_type: 'test',
    pass_condition: 'CBR medido ≥ CBR proyecto',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1534',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'CBR',
  },
  {
    code: 'PAV-031',
    category: 'pavement',
    subcategory: 'base',
    phase: 'during',
    description_es: 'Índice de Plasticidad de base < 6%',
    measurement_type: 'test',
    pass_condition: 'IP < 6%',
    min_value: null,
    max_value: 6,
    tolerance: null,
    unit: '%',
    severity: 'critical',
    reference_standard: 'NCh 1517',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Límites de Atterberg',
  },
  {
    code: 'PAV-032',
    category: 'pavement',
    subcategory: 'base',
    phase: 'during',
    description_es: 'Espesor de capa de base según diseño',
    measurement_type: 'measurement',
    pass_condition: 'Espesor = Espesor diseño ± tolerancia',
    min_value: null,
    max_value: null,
    tolerance: 1,
    unit: 'cm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-033',
    category: 'pavement',
    subcategory: 'base',
    phase: 'during',
    description_es: 'Compactación de base ≥ 95% Proctor Modificado',
    measurement_type: 'test',
    pass_condition: 'Compactación ≥ 95% PM',
    min_value: 95,
    max_value: null,
    tolerance: null,
    unit: '%PM',
    severity: 'critical',
    reference_standard: 'NCh 1515',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Densidad in-situ',
  },

  // === ASPHALT PAVEMENT ===
  {
    code: 'PAV-040',
    category: 'pavement',
    subcategory: 'asphalt_binder',
    phase: 'during',
    description_es: 'Diseño de mezcla de Binder actualizado con VºBº del ITO, previo al asfaltado',
    measurement_type: 'documentation',
    pass_condition: 'Diseño de mezcla aprobado por ITO',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Diseño Marshall',
  },
  {
    code: 'PAV-041',
    category: 'pavement',
    subcategory: 'asphalt_surface',
    phase: 'during',
    description_es: 'Diseño de mezcla de Carpeta actualizado con VºBº del ITO, previo al asfaltado',
    measurement_type: 'documentation',
    pass_condition: 'Diseño de mezcla aprobado por ITO',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: true,
    test_method: 'Diseño Marshall',
  },

  // === CONCRETE PAVEMENT AND SIDEWALKS ===
  {
    code: 'PAV-050',
    category: 'pavement',
    subcategory: 'concrete_pavement',
    phase: 'during',
    description_es: 'Hormigón de Calzada HF 5.0 - tomar muestras de hormigón en fresco (probetas cúbicas)',
    measurement_type: 'test',
    pass_condition: 'Resistencia flexotracción ≥ 5.0 MPa',
    min_value: 5.0,
    max_value: null,
    tolerance: null,
    unit: 'MPa',
    severity: 'critical',
    reference_standard: 'NCh 170',
    requires_photo: true,
    requires_lab_test: true,
    test_method: 'Flexotracción',
  },
  {
    code: 'PAV-051',
    category: 'pavement',
    subcategory: 'sidewalk',
    phase: 'during',
    description_es: 'Accesos unifamiliares con paquete estructural de veredas reforzadas, e=10cm, paño contiguo de 1m mínimo por lado',
    measurement_type: 'measurement',
    pass_condition: 'Espesor = 10 cm, largo paño ≥ 1 m',
    min_value: 10,
    max_value: null,
    tolerance: null,
    unit: 'cm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-052',
    category: 'pavement',
    subcategory: 'sidewalk',
    phase: 'during',
    description_es: 'Pendiente transversal máxima de veredas 2%',
    measurement_type: 'measurement',
    pass_condition: 'Pendiente ≤ 2%',
    min_value: null,
    max_value: 2,
    tolerance: null,
    unit: '%',
    severity: 'major',
    reference_standard: 'OGUC',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Nivel',
  },
  {
    code: 'PAV-053',
    category: 'pavement',
    subcategory: 'sidewalk',
    phase: 'during',
    description_es: 'Veredas despejadas y sin elementos que las obstaculicen',
    measurement_type: 'visual',
    pass_condition: 'Sin obstrucciones',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'major',
    reference_standard: 'OGUC',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },

  // === CURBS ===
  {
    code: 'PAV-060',
    category: 'pavement',
    subcategory: 'curbs',
    phase: 'during',
    description_es: 'Largo máximo solera rebajada 14 metros',
    measurement_type: 'measurement',
    pass_condition: 'Largo ≤ 14 m',
    min_value: null,
    max_value: 14,
    tolerance: null,
    unit: 'm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-061',
    category: 'pavement',
    subcategory: 'curbs',
    phase: 'during',
    description_es: 'Acceso en zona de veredas no superar los 7.5 metros de ancho',
    measurement_type: 'measurement',
    pass_condition: 'Ancho acceso ≤ 7.5 m',
    min_value: null,
    max_value: 7.5,
    tolerance: null,
    unit: 'm',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-062',
    category: 'pavement',
    subcategory: 'curbs',
    phase: 'during',
    description_es: 'Dispositivos de Rodados: mínimo 1.2 metros de solera rebajada con plinto 0 cm',
    measurement_type: 'measurement',
    pass_condition: 'Ancho ≥ 1.2 m, plinto = 0 cm',
    min_value: 1.2,
    max_value: null,
    tolerance: null,
    unit: 'm',
    severity: 'major',
    reference_standard: 'OGUC',
    requires_photo: true,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },
  {
    code: 'PAV-063',
    category: 'pavement',
    subcategory: 'curbs',
    phase: 'during',
    description_es: 'Soleras tipo C, longitud 0.50 m',
    measurement_type: 'measurement',
    pass_condition: 'Longitud = 0.50 m',
    min_value: 0.50,
    max_value: 0.50,
    tolerance: 0.02,
    unit: 'm',
    severity: 'minor',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: 'Medición directa',
  },

  // === STORMWATER DRAINAGE TESTS ===
  {
    code: 'ALL-020',
    category: 'stormwater',
    subcategory: 'testing',
    phase: 'during',
    description_es: 'Pruebas de hermeticidad de Colectores',
    measurement_type: 'test',
    pass_condition: 'Sin fugas detectadas',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: 'Prueba hidrostática',
  },
  {
    code: 'ALL-021',
    category: 'stormwater',
    subcategory: 'testing',
    phase: 'final_reception',
    description_es: 'Prueba de escurrimiento superficial de aguas para detectar puntos bajos y operatividad de sumideros, colectores y zanjas de infiltración',
    measurement_type: 'test',
    pass_condition: 'Escurrimiento sin emposamiento, sumideros operativos',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: 'Prueba de inundación',
  },
  {
    code: 'ALL-022',
    category: 'stormwater',
    subcategory: 'drainage',
    phase: 'final_reception',
    description_es: 'Aguas lluvias del privado no escurren al sector público',
    measurement_type: 'visual',
    pass_condition: 'Drenaje contenido en propiedad privada',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'ALL-023',
    category: 'stormwater',
    subcategory: 'inlets',
    phase: 'during',
    description_es: 'No construir sumideros frente a soleras rebajadas (solo nuevas urbanizaciones)',
    measurement_type: 'visual',
    pass_condition: 'Sumideros alejados de soleras rebajadas',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },

  // === FINAL RECEPTION ===
  {
    code: 'REC-001',
    category: 'final_reception',
    subcategory: 'condition',
    phase: 'final_reception',
    description_es: 'Evaluar estado de pavimentos, soleras y veredas existentes en todos los frentes con respecto de su estado inicial',
    measurement_type: 'visual',
    pass_condition: 'Estado igual o mejor al inicial',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'REC-002',
    category: 'final_reception',
    subcategory: 'completion',
    phase: 'final_reception',
    description_es: 'Obra físicamente terminada de acuerdo a Proyecto original, Plano As-Built o Modificación aprobada',
    measurement_type: 'visual',
    pass_condition: 'Obra conforme a planos aprobados',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: true,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'REC-003',
    category: 'final_reception',
    subcategory: 'site_visit',
    phase: 'final_reception',
    description_es: 'Última visita realizada en no más de 10 días hábiles desde el primer ingreso de certificación de calidad',
    measurement_type: 'administrative',
    pass_condition: 'Visita dentro de 10 días hábiles',
    min_value: null,
    max_value: 10,
    tolerance: null,
    unit: 'días',
    severity: 'major',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'REC-004',
    category: 'final_reception',
    subcategory: 'documentation',
    phase: 'final_reception',
    description_es: 'Certificación de Calidad aprobada',
    measurement_type: 'documentation',
    pass_condition: 'Certificación aprobada',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'REC-005',
    category: 'final_reception',
    subcategory: 'guarantee',
    phase: 'final_reception',
    description_es: 'Boleta de garantía certificada',
    measurement_type: 'documentation',
    pass_condition: 'Boleta vigente y certificada',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: null,
  },
  {
    code: 'REC-006',
    category: 'final_reception',
    subcategory: 'documentation',
    phase: 'final_reception',
    description_es: 'Pase a Comisión: Libro de obras firmado, Formulario Nº3, Check list F8',
    measurement_type: 'documentation',
    pass_condition: 'Documentación completa',
    min_value: null,
    max_value: null,
    tolerance: null,
    unit: null,
    severity: 'critical',
    reference_standard: 'SERVIU',
    requires_photo: false,
    requires_lab_test: false,
    test_method: null,
  },
];

async function importCriteria() {
  console.log('Importing verification criteria...\n');

  const db = createClient({
    url: 'file:local.db',
  });

  // Ensure table exists
  await db.execute(`
    CREATE TABLE IF NOT EXISTS verification_criteria (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      category TEXT NOT NULL,
      subcategory TEXT,
      phase TEXT NOT NULL,
      description_es TEXT NOT NULL,
      description_en TEXT,
      measurement_type TEXT,
      pass_condition TEXT,
      min_value REAL,
      max_value REAL,
      tolerance REAL,
      unit TEXT,
      severity TEXT NOT NULL DEFAULT 'major',
      reference_standard TEXT,
      reference_section TEXT,
      source_document TEXT,
      requires_photo INTEGER DEFAULT 0,
      requires_lab_test INTEGER DEFAULT 0,
      test_method TEXT,
      is_active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )
  `);

  await db.execute(`CREATE INDEX IF NOT EXISTS idx_verification_criteria_code ON verification_criteria(code)`);
  await db.execute(`CREATE INDEX IF NOT EXISTS idx_verification_criteria_category ON verification_criteria(category)`);
  await db.execute(`CREATE INDEX IF NOT EXISTS idx_verification_criteria_phase ON verification_criteria(phase)`);

  let inserted = 0;
  let skipped = 0;

  for (const criterion of verificationCriteria) {
    try {
      // Check if exists
      const existing = await db.execute({
        sql: 'SELECT id FROM verification_criteria WHERE code = ?',
        args: [criterion.code],
      });

      if (existing.rows.length > 0) {
        skipped++;
        continue;
      }

      const id = `vc_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;

      await db.execute({
        sql: `INSERT INTO verification_criteria (
          id, code, category, subcategory, phase, description_es,
          measurement_type, pass_condition, min_value, max_value, tolerance, unit,
          severity, reference_standard, requires_photo, requires_lab_test, test_method,
          source_document, is_active
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        args: [
          id,
          criterion.code,
          criterion.category,
          criterion.subcategory,
          criterion.phase,
          criterion.description_es,
          criterion.measurement_type,
          criterion.pass_condition,
          criterion.min_value,
          criterion.max_value,
          criterion.tolerance,
          criterion.unit,
          criterion.severity,
          criterion.reference_standard,
          criterion.requires_photo ? 1 : 0,
          criterion.requires_lab_test ? 1 : 0,
          criterion.test_method,
          'Check_List_Inspeccion.pdf',
          1,
        ],
      });

      inserted++;
    } catch (error) {
      console.error(`Error inserting ${criterion.code}:`, error);
    }
  }

  // Print summary
  console.log('=' .repeat(60));
  console.log('IMPORT SUMMARY');
  console.log('=' .repeat(60));
  console.log(`Total criteria: ${verificationCriteria.length}`);
  console.log(`Inserted: ${inserted}`);
  console.log(`Skipped (duplicates): ${skipped}`);

  // Count by category
  const byCategory: Record<string, number> = {};
  const byPhase: Record<string, number> = {};
  const bySeverity: Record<string, number> = {};

  for (const c of verificationCriteria) {
    byCategory[c.category] = (byCategory[c.category] || 0) + 1;
    byPhase[c.phase] = (byPhase[c.phase] || 0) + 1;
    bySeverity[c.severity] = (bySeverity[c.severity] || 0) + 1;
  }

  console.log('\nBy Category:');
  Object.entries(byCategory).sort((a, b) => b[1] - a[1]).forEach(([cat, count]) => {
    console.log(`  ${cat}: ${count}`);
  });

  console.log('\nBy Phase:');
  Object.entries(byPhase).sort((a, b) => b[1] - a[1]).forEach(([phase, count]) => {
    console.log(`  ${phase}: ${count}`);
  });

  console.log('\nBy Severity:');
  Object.entries(bySeverity).sort((a, b) => b[1] - a[1]).forEach(([sev, count]) => {
    console.log(`  ${sev}: ${count}`);
  });

  console.log('\n✅ Import complete!');
}

importCriteria().catch(console.error);
